Added support to add and track the ref url parameter that speechly.co…
speechly/demo-navigation pull request #21
Opened 2023-02-07 11:17 UTC by nameisxi

…m adds

2023-02-07 11:30 UTC, thisismatu requested changes

2023-02-07 11:30 UTC, thisismatu commented on src/components/DemoNavigation.tsx
> +const currentUrl = window.location.href.split(/[?#]/)[0];
To improve readability later on i would remove the comments and instead of regex splitting just use `window.location.origin + window.location.pathname`.

2023-02-07 11:30 UTC, thisismatu commented on src/components/DemoNavigation.tsx
> +// Finds the referring url that speechly.com adds. If traffic is outside of speechly.com, document.referrer is used.
I would remove comments, the code itself is clear enough

2023-02-07 11:30 UTC, thisismatu commented on src/components/DemoNavigation.tsx
> +  // if full url (e.g. https://www.demos.speechly.com/transcription), split from .com and keep only the route portion (e.g. /transcription).
If you are only interested in the pathname, why not refactor this to convert the string to a URL object and the just get the pathname from there? It would improve the readability of the code and would allow you to remove the comments.

For example:

```
const url = new URL(urlString)
url.pathname
```

2023-02-08 09:39 UTC, nameisxi commented on src/components/DemoNavigation.tsx
> +  // if full url (e.g. https://www.demos.speechly.com/transcription), split from .com and keep only the route portion (e.g. /transcription).
Good idea 👍

2023-02-08 09:42 UTC, thisismatu approved these changes

2023-02-08 10:29 UTC, merged